jobs:
  build:
    name: Workflow
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Prerequisites
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Check
        run: ./ci/action

name: Check

on:
  schedule:
    - cron: "35 0/3 * * *"
